url = "http://localhost:2368"

[mail]
#transport = "SMTP"

  #[mail.options]
  #service = "Mailgun"

    #[mail.options.auth]
    #user = "username@hostname.mailgun.org"
    #pass = "password"

[server]
ip = "0.0.0.0"
port = "2368"
