version: '2'
services:
  ghost:
    image: cnunciato/ghost
    environment:
      - HAB_GHOST=${HAB_GHOST}
    ports:
      - 1337:1337
    volumes:
      - ./themes:/hab/svc/ghost/data/themes
      - ./user.toml:/hab/svc/ghost/user.toml
